


[font]
size = 9

[font.normal]
family = "monospace"


[font.bold]
family = "monospace"

[font.italic]
family = "monospace"

[general]
import = ["~/.config/alacritty/themes/themes/dracula.toml"]


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
